name: Matrix Cron Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1"

jobs:
  tags:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.fetcher.outputs.matrix }}
    defaults:
      run:
        working-directory: tags
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm i
      - run: node .

  build:
    runs-on: ubuntu-latest
    needs: tags
    strategy:
      matrix: ${{fromJson(needs.tags.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Extract tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: ${{ matrix.tags }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: NGINX=${{ matrix.version }}
          tags: ${{ steps.meta.outputs.tags }}
